spring.cloud.config.uri=http://config-server:8888
spring.cloud.config.fail-fast=false
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Zipkin tracing
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1

# CORS Configuration
spring.cloud.gateway.globalcors.corsConfigurations['[/**]'].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.corsConfigurations['[/**]'].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations['[/**]'].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations['[/**]'].allowCredentials=true
spring.cloud.gateway.globalcors.corsConfigurations['[/**]'].exposedHeaders=Authorization
