spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2580
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info
